spring.application.name=demo
server.port=8000


spring.database.url=jdbc:mysql://192.168.106.201:3306/hr?useSSL=false&serverTimezone=UTC

spring.datasource.username=hr-api

spring.datasource.password=123456

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
